"""empty message

Revision ID: 0c20704b185f
Revises: 233dd685fdfb
Create Date: 2016-02-24 23:53:58.776891

"""

# revision identifiers, used by Alembic.
revision = '0c20704b185f'
down_revision = '233dd685fdfb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    ### end Alembic commands ###
