"""empty message

Revision ID: 8761da0f7b32
Revises: be04edfbb1c2
Create Date: 2016-02-25 02:00:42.092088

"""

# revision identifiers, used by Alembic.
revision = '8761da0f7b32'
down_revision = 'be04edfbb1c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
